
services:
    db:
        container_name: cadastro_database
        image: postgres:16-alpine
        environment:
            - POSTGRES_DB=web
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data  
    redis:
        image: "redis:alpine"
    web:
        build: .
        volumes:
            - webserver_media:/code/media
        command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py collectstatic --noinput && python /code/manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - redis
            - db
    celery:
        build: .
        command: bash -c "celery -A {{cookiecutter.project_slug}} worker -Q celery --autoscale=5,3 -l info"
        volumes:
            - webserver_media:/code/media
        depends_on:
            - redis
    celery-beat:
        build: .
        volumes:
            - webserver_media:/code/media
        command: celery -A {{cookiecutter.project_slug}} beat -l info
        depends_on:
            - redis

    volumes:
        pgdata: {}
        webserver_media: {}
        node-modules: